repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix ]
        types_or: [python, jupyter]
      - id: ruff-format
        args: [ --preview ]
        types_or: [python, jupyter]
